### ISSUE TITLE
Chart not refreshing

### ISSUE THREAD

**Issue by RusEu** [C451/trading-vue-js#63] opened 2019-09-26 18:16 UTC
It only happens to me or there is a bug in the repo?
I tried to cloning the git project and also tried with the library.
I don't think is a problem with my pc, since I can see the demo without any problem

![error](https://user-images.githubusercontent.com/11183790/65713878-607e8300-e09a-11e9-9cbc-4ba04302204e.png)

**Comment by C451** [comment] 2019-09-26 18:57
Could you provide full info about your setup?  OS, Browser, node version. Do you run the default `npm run dev` or `npm run test`? 

Couldn't reproduce on my side.

**Comment by RusEu** [comment] 2019-09-26 19:39
- using Arch Linux(Manjaro).
- executing with  npm run dev
- with version 0.3.3 works perfect :-)

**Comment by C451** [comment] 2019-09-26 19:53
> Arch Linux(Manjaro).
That's pretty exotic :) I have only ubuntu, will try on it.

If it's not a problem, could find out which version introduced the bug? Is it 0.3.3 -> 0.3.4 ?

**Comment by C451** [comment] 2019-09-26 20:09
Yeah, couldn't catch on ubuntu either.

**Comment by RusEu** [comment] 2019-09-26 21:14
Above 0.3.3 the library crashes.
I saw that you added some support for retina display on version 0.3.4, maybe that could be the reason of the issue.
But if you don't think is a real problem that needs to be solved, I'm fine using the 0.3.3 :blush:

**Comment by C451** [comment] 2019-09-27 09:07
Thanks! This problem needs to be solved, but without the proper setup it's near to impossible. 

I've spent a hell lot of time on retina support, for some reason this was the trickiest part of the development. 

Using 0.3.3, you will miss out on many great features! :)

**Comment by C451** [comment] 2019-09-29 08:36
Ok, closing until someone hits this again, need more data.

**Closed by C451** 2019-09-29 08:36 UTC

**Comment by 1am** [comment] 2019-10-12 10:22
Hi. I've bumped into same issue on OSX running the example from https://github.com/C451/trading-vue-js#how-to-use added in Nuxt.js boilerplate code.

This happens in Brave browser ( `Version 0.68.131 Chromium: 76.0.3809.100 (Official Build)` ) and in Chrome ( `Version 77.0.3865.90 (Official Build) (64-bit)` ) it's all ok. I'll just use Chrome, not a problem for me, just sharing info.

![Screen Shot 2019-10-12 at 12 20 44](https://user-images.githubusercontent.com/959323/66699863-cbf76000-ecea-11e9-9a9c-a290cedbadbb.png)

**Comment by C451** [comment] 2019-10-13 16:37
@1am Hi, that's interesting, couldn't catch this in Brave with `npm run test`, maybe it's because of Nuxt.js? The glitch looks dope tho.

**Comment by 1am** [comment] 2019-10-13 17:25
Actually I had the same behaviour in Brave with npm run test. I guess it's some combination of hardware and OS + specific browser since standard Chrome or Safari work fine on OSX.
Repeated similar thing on Ubuntu Mate Linux - Brave not ok / Chrome ok.  

Indeed looks interesting

![Screen Shot 2019-10-13 at 19 21 14](https://user-images.githubusercontent.com/959323/66719339-aa7f9c80-edee-11e9-9fac-01db5ae74dd5.png)

**Comment by C451** [comment] 2019-10-13 18:12
I guess it caused by the retina code, without this block https://github.com/C451/trading-vue-js/blob/master/src/mixins/canvas.js#L12 should work fine. 

The lazy solution is to add the `retinaSupport` flag.
